// Minimal PDF generation using jsPDF. Requires `jspdf` dependency.
// Install: npm install jspdf
import { jsPDF } from "jspdf";

export async function generateParcelPdf(parcel: any) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const lines = [] as string[];
  lines.push(`Tracking ID: ${parcel.trackingId || parcel.id || "-"}`);
  lines.push(`Sender: ${parcel.senderName || parcel.sender?.name || "-"}`);
  lines.push(`Receiver: ${parcel.receiverName || parcel.receiver?.name || parcel.receiverEmail || "-"}`);
  const addr = parcel.receiverAddress || parcel.receiver?.address || {};
  lines.push(`Address: ${addr.street || ""}, ${addr.city || ""}, ${addr.state || ""} ${addr.zipCode || ""}`);
  lines.push(`Type: ${parcel.parcelDetails?.type || parcel.type || "-"}`);
  lines.push(`Weight: ${parcel.parcelDetails?.weight || "-"} kg`);

  doc.setFontSize(14);
  doc.text("Parcel Details", 40, 60);
  doc.setFontSize(11);
  let y = 90;
  lines.forEach((line) => {
    doc.text(line, 40, y);
    y += 20;
  });

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ParcelTrack", 40, 780);

  doc.save(`parcel_${parcel.trackingId || parcel.id || Date.now()}.pdf`);
}
